# Generated by Django 5.2.8 on 2025-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_normalized_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
